/** Stable logical sound IDs. Replace tmp_<id>.mp3 with <id>.mp3 to add a real effect. */
export const SOUND_NAMES = [
  "groan",
  "burble",
  "splash",
  "spike",
  "jelly_pop",
  "deflate",
  "release",
  "accident",
  "zap",
  "balloon_pop",
  "chute_open",
  "basket_landed",
  "burner",
  "splat",
  "hit",
  "shutter",
  "camera_beep",
  "smash",
  "slingshot_draw",
  "slingshot_fire",
  "bonk",
  "pebble_shot",
  "ricochet",
  "kid_cry",
  "beep",
  "sad_trombone",
  "wedding_arrived",
  "wedding_beat",
  "wedding_kiss",
  "wedding_ruined",
  "wedding_married",
  "bouquet_thrown",
  "bouquet_caught",
  "bouquet_hit"
] as const;
export type SoundName = (typeof SOUND_NAMES)[number];
